#!/bin/bash

DEFAULT_DOCROOT_SUFFIX="public"
DEFAULT_FAKE_HTTPS="on"

[[ -z "${DOCROOT_SUFFIX}" ]] && docroot_suffix_value=${DEFAULT_DOCROOT_SUFFIX} || docroot_suffix_value="${DOCROOT_SUFFIX}"

if [[ -z "${FAKE_HTTPS}" ]]; then
    fake_https_value=${DEFAULT_FAKE_HTTPS}
else
    if [ "${FAKE_HTTPS}" == "on" ] || [ "${FAKE_HTTPS}" == "off" ]; then
        fake_https_value=${FAKE_HTTPS}
    else
        fake_https_value=${DEFAULT_FAKE_HTTPS}
    fi
fi

if [ ! -f "/etc/nginx/conf.d/default.conf.original" ]; then
    cp /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.original
fi

sed \
    -e "s%__docroot_suffix__%${docroot_suffix_value}%g" \
    -e "s%__fake_https__%${fake_https_value}%g" \
    /etc/nginx/conf.d/default.conf.original > /etc/nginx/conf.d/default.conf

