#!/bin/bash

source hooks/.config

set -e

for phpversion in ${php_versions[@]}; do
    for purpose in ${build_purposes[@]}; do
        for arch in ${build_architectures[@]}; do
            if [ -d "purpose/${phpversion}/${purpose}" ]; then
                echo ">>> Build ${phpversion} ${purpose} for ${arch}, qemu architecture ${docker_qemu_arch_map[${arch}]}"

                BASE_IMAGE_PREFIX="${base_image_prefix_map[${arch}]}"

                docker build \
                    --no-cache \
                    --build-arg BASE_IMAGE_PREFIX=${BASE_IMAGE_PREFIX} \
                    --build-arg ARCH=${docker_qemu_arch_map[${arch}]} \
                    --build-arg PURPOSE=${purpose} \
                    --build-arg PHPVERSION=${phpversion} \
                    --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
                    --tag "${DOCKER_REPO}:${phpversion}-${purpose}-${arch}" \
                    -f purpose/${phpversion}/${purpose}/Dockerfile \
                    .
            fi
        done
    done
done
