#!/bin/bash

source hooks/.config

for phpversion in ${php_versions[@]}; do
    for purpose in ${build_purposes[@]}; do
        for arch in ${build_architectures[@]}; do
            if [ -d "purpose/${phpversion}/${purpose}" ]; then
                docker push "${DOCKER_REPO}:${phpversion}-${purpose}-${arch}"

                if ["${phpversion}" = "php7"] && [ "${purpose}" = "general" ] && [ "${arch}" = "amd64" ]; then
                    docker tag "${DOCKER_REPO}:${phpversion}-${purpose}-${arch}" "${IMAGE_NAME}"
                    docker push "${IMAGE_NAME}"
                fi
            fi
        done
    done
done
